version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/analyst-toolkit
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ssm-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ssm-user
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ssm-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ssm-user
